"""Initial schema

Revision ID: 3f379d39b4c1
Revises: 
Create Date: 2025-04-14 20:20:51.834380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f379d39b4c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_location_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_parking_slots_slot_number')
        batch_op.create_unique_constraint('unique_slot_per_location', ['parking_location_id', 'slot_number'])
        batch_op.create_foreign_key(None, 'parking_locations', ['parking_location_id'], ['id'])
        batch_op.drop_column('location')
        batch_op.drop_column('coordinates')
        op.drop_column('parking_locations', 'available_slots')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_slot_per_location', type_='unique')
        batch_op.create_index('ix_parking_slots_slot_number', ['slot_number'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('parking_location_id')

    # ### end Alembic commands ###
